#!/bin/bash

set -e

docker info &>/dev/null || sudo start docker

TAG="$1"
docker build -t unruh/isabelle:"$TAG" -f Dockerfile."$TAG" .
docker login -u unruh -e dominique@unruh.de
docker push unruh/isabelle:"$TAG"
